intro:
title: A Dataset Perspective on Offline Reinforcement Learning
description:
- Conference on Lifelong Learning Agents 2022 (Oral)
buttons:
  Paper: 'https://arxiv.org/abs/2111.04714'
  Code: 'https://github.com/ml-jku/OfflineRL'
  Slides: 'pdfs/slides.pdf'
  Poster: 'pdfs/poster.pdf'
kramdown:
  math_engine: mathjax
theme: jekyll-theme-cayman

google_analytics: G-D8TNX1TGTY
