name: offline_rl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - matplotlib
  - seaborn
  - pytorch=1.8.1
  - torchvision
  - torchaudio
  - cudatoolkit=11
  - pip:
      - tensorboard
      - hyperloglog
      - gym
      - gym-minigrid
      - pygame
      - git+https://github.com/ntasfi/PyGame-Learning-Environment.git
      - git+https://github.com/kschweig/MinAtar.git
      - git+https://github.com/kschweig/gym-games.git